Traceback (most recent call last):
  File "yolov5_lightning.py", line 156, in <module>
    data_module = CustomDataModule(
  File "yolov5_lightning.py", line 60, in __init__
    all_data = pd.read_csv(label_file)
  File "/apps/easybuild/software/tinkercliffs-rome_dgx-a100/Anaconda3/2020.11/lib/python3.8/site-packages/pandas/io/parsers.py", line 686, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/apps/easybuild/software/tinkercliffs-rome_dgx-a100/Anaconda3/2020.11/lib/python3.8/site-packages/pandas/io/parsers.py", line 452, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/apps/easybuild/software/tinkercliffs-rome_dgx-a100/Anaconda3/2020.11/lib/python3.8/site-packages/pandas/io/parsers.py", line 946, in __init__
    self._make_engine(self.engine)
  File "/apps/easybuild/software/tinkercliffs-rome_dgx-a100/Anaconda3/2020.11/lib/python3.8/site-packages/pandas/io/parsers.py", line 1178, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/apps/easybuild/software/tinkercliffs-rome_dgx-a100/Anaconda3/2020.11/lib/python3.8/site-packages/pandas/io/parsers.py", line 2008, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] No such file or directory: '/home/shihong/data/mock_lightning/train/label.csv'
